var imgTitles = [
    'Màn hình khởi động, người dùng có thể chọn load lại các cài đặt cũ hoặc tạo mới',
    'Hướng dẫn, chạm và giữ hình nền để vào chế độ thiết lập',
    'Màn hình mặc định',
    'Phân chia ứng dụng theo thể loại, các ứng dụng cùng loại được xếp trong cùng thư mục',
    'Màn hình tổng quan',
    'Thay đổi hình nền',
    'Chọn widgets',
    'Cài đặt launcher',
    'Menu phụ',
    'Chế độ xem dạng lưới',
    'Tìm kiếm nhanh ứng dụng',
    'Sắp xếp các ứng dụng',
    'Chế độ xem dạng danh sách',
    'Thư mục',
    'Thay đổi icon, launcher gợi ý cho người dùng 3 gói icon là Numix Circle, Numix Fold, Moonshine, ngoài ra còn rất nhiều gói khác có thể tải từ Google Play',
    'Icon Numix Circle',
    'Icon Moonshine',
    'Icon Flat',
    'Icon Sunshine',
    'Icon Numix Fold',
    'Thay đổi theme',
    'Theme Bluesky, mặc định',
    'Theme Blue',
    'Theme Green',
    'Chế độ trong suốt hình nền',
    'Nửa trong suốt',
    'Trong suốt hoàn toàn',
    'Thay đổi màu chữ',
    'Chế độ cuộn nhanh trong list view',
    'Kéo thả icon tạo shorcut hoặc gỡ bõ hoặc xem thông tin về ứng dụng'
]
